name: Build Container Images

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  # Run the linter
  lint:
    name: Linter
    runs-on: ubuntu-22.04

    # Grant status permission for MULTI_STATUS on Super-Linter
    permissions:
      contents: read
      packages: read
      statuses: write


    steps:
      - name: Git Code Checkout
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Linters to enable
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_YAML: true


  # Build the container images
  build-certificate-manager:
    name: Build Certificate Manager
    runs-on: ubuntu-22.04

    steps:
      - name: Git Code Checkout
        uses: actions/checkout@v3

        # For building ARM64 images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.11.2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
